"""first_revision_of_npg_porch_schema

Revision ID: bb1c7a5b3a1a
Revises:
Create Date: 2026-02-26 15:15:08.165136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb1c7a5b3a1a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic and checked ###
    op.create_table(
        "npg_porch.pipeline",
        sa.Column("pipeline_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("repository_uri", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("pipeline_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "npg_porch.task",
        sa.Column("task_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("job_descriptor", sa.String(), nullable=True),
        sa.Column("definition", sa.JSON(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("prefix", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["npg_porch.pipeline.pipeline_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
        sa.UniqueConstraint("pipeline_id", "job_descriptor", name="unique_tasks"),
    )
    op.create_index(
        "idx_ordered_tasks", "npg_porch.task", ["pipeline_id", "created"], unique=False
    )
    op.create_table(
        "npg_porch.token",
        sa.Column("token_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=32), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("date_issued", sa.DateTime(), nullable=True),
        sa.Column("date_revoked", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["npg_porch.pipeline.pipeline_id"],
        ),
        sa.PrimaryKeyConstraint("token_id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "npg_porch.event",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("change", sa.String(), nullable=True),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["npg_porch.task.task_id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["token.token_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop everything."""
    # ### commands auto generated by Alembic and checked ###
    op.drop_table("npg_porch.event")
    op.drop_table("npg_porch.token")
    op.drop_index("idx_ordered_tasks", table_name="npg_porch.task")
    op.drop_table("npg_porch.task")
    op.drop_table("npg_porch.pipeline")
    # ### end Alembic commands ###
